// SPDX-License-Identifier: Apache-2.0
export const LENS_STYLE = `
.fc-lens{--accent:#e8a33d;--line:#34343f;color:#e6e6ee;background:#131317;border:1px solid #454550;border-radius:10px;padding:0;width:min(1420px,96vw);max-width:96vw;height:min(900px,94vh);max-height:94vh;box-sizing:border-box;font:13px/1.45 system-ui,sans-serif;box-shadow:0 24px 90px #000b;overflow:hidden}
.fc-lens[open]{display:flex;flex-direction:column}.fc-lens::backdrop{background:#07090bca}.fc-lens *{box-sizing:border-box}.fc-lens [hidden]{display:none!important}
.fc-lens h2,.fc-lens h3,.fc-lens p{margin:0}.fc-lens h2{font-size:21px;letter-spacing:-.5px}.fc-lens h3{font-size:13px}.fc-lens small,.fc-lens .muted{color:#a8a8b6;font-size:12px}
.fc-lens header,.fc-lens footer{display:flex;align-items:center;gap:16px;padding:14px 20px;background:#1b1b21;flex-shrink:0}.fc-lens header{border-bottom:1px solid var(--line)}.fc-lens header .brand{flex:1;display:flex;gap:14px;align-items:center}.fc-lens .brand-mark{display:grid;place-items:center;border:1px solid #82602f;border-radius:50%;width:36px;height:36px;color:#edb365;font-size:23px;background:radial-gradient(circle,#4a3926,#1b1b21 70%)}.fc-lens .badge{color:#dca85d;font-size:10px;letter-spacing:.14em;text-transform:uppercase}.fc-lens footer{border-top:1px solid var(--line)}.fc-lens footer .muted{flex:1}
.fc-lens button,.fc-lens select,.fc-lens input[type=number]{font:inherit;color:inherit;background:#26262f;border:1px solid #454551;border-radius:5px;padding:7px 10px}.fc-lens button{cursor:pointer}.fc-lens button:hover{border-color:var(--accent)}.fc-lens button.primary{background:var(--accent);border-color:var(--accent);color:#1d160c;font-weight:650}.fc-lens button:disabled{opacity:.45;cursor:default}.fc-lens button:focus-visible,.fc-lens input:focus-visible,.fc-lens select:focus-visible,.fc-lens summary:focus-visible{outline:2px solid var(--accent);outline-offset:2px}.fc-lens input[type=checkbox],.fc-lens input[type=range]{accent-color:var(--accent)}
.fc-lens .modebar{display:flex;align-items:center;gap:18px;padding:10px 20px;border-bottom:1px solid var(--line);flex-shrink:0}.fc-lens .tabs{display:flex;gap:3px;padding:3px;border:1px solid var(--line);border-radius:7px;background:#101014}.fc-lens .tabs button{min-width:104px;background:transparent;border-color:transparent;padding:6px 16px;color:#aaaab8}.fc-lens .tabs button[aria-selected=true]{background:#33291d;color:#ffcc80;border-color:#76552b}.fc-lens .mode-description{color:#aaaab8;font-size:12px}
.fc-lens .layout{display:grid;grid-template-columns:300px minmax(0,1fr);flex:1;min-height:0;overflow:hidden}.fc-lens .sidebar{padding:18px;overflow:auto;border-right:1px solid var(--line);background:#19191f;scrollbar-width:thin;scrollbar-color:#686471 #19191f;min-width:0}.fc-lens .center{padding:16px 18px;min-width:0;min-height:0;display:flex;flex-direction:column;gap:10px;overflow:hidden}
.fc-lens .eyebrow{color:#b7a27f;font-size:10px;letter-spacing:.13em;text-transform:uppercase;margin-bottom:10px}.fc-lens .section-copy{font-size:12px;color:#a8a8b6;margin:5px 0 12px}.fc-lens .look-cards{display:grid;grid-template-columns:1fr 1fr;gap:8px}.fc-lens .look-card{text-align:left;min-height:76px;padding:10px;background:#202027;display:flex;flex-direction:column;gap:5px}.fc-lens .look-card[aria-pressed=true]{border-color:#dca04b;background:#30271c}.fc-lens .look-card strong{font-size:13px}.fc-lens .look-card small{font-size:10px;color:#aaa7a3}.fc-lens .palette{height:3px;width:34px;border-radius:3px;background:linear-gradient(90deg,#82c2d3,#c3916e,#a497c5)}.fc-lens .look-card[data-look=cool] .palette{background:linear-gradient(90deg,#78cedf,#4778b4)}.fc-lens .look-card[data-look=warm] .palette{background:linear-gradient(90deg,#f2c377,#a87551)}.fc-lens .look-card[data-look=bare] .palette{background:linear-gradient(90deg,#bbb,#727272)}.fc-lens .current-look{font-size:12px;color:#d8bd95;margin:10px 0 18px}
.fc-lens .field{display:block;margin:14px 0}.fc-lens .field-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:6px}.fc-lens .field-head>span{display:inline-flex;align-items:center;gap:5px}.fc-lens .field output{color:#f3c17b;font-variant-numeric:tabular-nums;font-size:12px;white-space:nowrap}.fc-lens .field input[type=range]{width:100%;display:block;height:16px;margin:0}.fc-lens select{width:100%;min-height:34px}.fc-lens .check{display:flex;gap:8px;align-items:flex-start;margin:12px 0}.fc-lens .check input{margin:3px 0}.fc-lens .check>span{display:inline-flex;gap:6px;align-items:center;flex-wrap:wrap}.fc-lens .divider{border-top:1px solid var(--line);margin:20px 0}.fc-lens .output-note{padding:10px 12px;border-radius:5px;background:#242119;border:1px solid #51422f;color:#d4ba90;font-size:12px;margin:12px 0}
.fc-lens details.control-section{border:1px solid var(--line);border-radius:6px;margin:0 0 9px;background:#1c1c23}.fc-lens .control-section>summary{padding:11px 12px;font-weight:600;color:#dedee8;cursor:pointer}.fc-lens .control-section[open]>summary{color:#f0bc75;border-bottom:1px solid var(--line)}.fc-lens .section-body{padding:0 12px 12px}.fc-lens .section-body .field:last-child{margin-bottom:2px}.fc-lens .surface-facts{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:10px 0}.fc-lens .surface-facts span{padding:8px;background:#131319;border-radius:4px;font-size:12px;color:#c5c5d0}.fc-lens .surface-facts small{display:block;font-size:10px;color:#888894}.fc-lens .pairs{max-height:210px;overflow:auto;display:grid;gap:5px;margin-top:10px;scrollbar-width:thin}.fc-lens .pair{display:flex;gap:8px;align-items:center}.fc-lens .pair button{flex:1;text-align:left;font-size:12px}.fc-lens .on{border-color:#d99d48!important;background:#30281d!important;color:#ffcc81!important}.fc-lens .search{width:100%;padding:8px;background:#101014;color:#ddd;border:1px solid #454551;border-radius:4px;font:inherit}
.fc-lens .preview-heading{display:flex;align-items:center;gap:10px;min-height:31px}.fc-lens .preview-heading h3{flex:1;font-size:13px;color:#dddde7}.fc-lens .preview-heading button{font-size:12px;padding:5px 9px}.fc-lens .previewspace{min-height:120px;flex:1;display:grid;place-items:center;overflow:hidden;background:radial-gradient(ellipse,#18181f,#0d0d11);border:1px solid #292932;border-radius:7px}.fc-lens .viewport{position:relative;background:#000;overflow:hidden;touch-action:none;cursor:crosshair;flex-shrink:0}.fc-lens canvas{display:block;width:100%;height:100%}.fc-lens .cross{position:absolute;width:16px;height:16px;border:1px solid #a4dfec;border-radius:50%;transform:translate(-50%,-50%);pointer-events:none}.fc-lens .cross:before,.fc-lens .cross:after{content:'';position:absolute;background:#a4dfec}.fc-lens .cross:before{width:22px;height:1px;left:-4px;top:7px}.fc-lens .cross:after{height:22px;width:1px;left:7px;top:-4px}.fc-lens .preview-caption{color:#9999a9;font-size:11px}.fc-lens .status{color:#b6a17f;min-height:17px;font-size:11px}.fc-lens .error{color:#ffbc9b}.fc-lens .coordinates{display:flex;gap:10px;flex-wrap:wrap}.fc-lens .coordinates label{flex:1}.fc-lens .coordinates input{width:100%;margin-top:5px}
.fc-lens .optics{border:1px solid #38404a;border-radius:7px;background:linear-gradient(125deg,#191d24,#111318);flex-shrink:0;overflow:hidden}.fc-lens .optics>summary{cursor:pointer;padding:10px 13px;display:flex;align-items:center;gap:8px;list-style:none;color:#d5dce5}.fc-lens .optics>summary::before{content:'›';font-size:18px;line-height:1;transition:transform .12s}.fc-lens .optics[open]>summary::before{transform:rotate(90deg)}.fc-lens .optics>summary small{margin-left:auto;font-size:10px;color:#8c9baa}.fc-lens .optics-body{padding:0 12px 9px}.fc-lens .diagram{height:162px;overflow:hidden}.fc-lens .diagram svg{display:block;width:100%;height:100%;overflow:visible}.fc-lens .surface{cursor:pointer}.fc-lens .surface:focus{outline:none}.fc-lens .surface:focus path:last-child{stroke:#fff;stroke-width:3.5}.fc-lens .diagram-footer{display:flex;align-items:center;gap:8px;flex-wrap:wrap;font-size:10px;color:#99a6b6}.fc-lens .diagram-footer .selected-readout{margin-left:auto;color:#92dbe6}.fc-lens .legend-dot{display:inline-block;width:6px;height:6px;border-radius:50%;background:#9db8c4;margin-right:4px}.fc-lens .legend-dot.bounce{background:#f2b65b}.fc-lens .legend-dot.glass{background:#82bccf}.fc-lens .diagram-empty{color:#8d9cac;padding:45px 20px;text-align:center}
.fc-lens[data-preview-state=pending] canvas,.fc-lens[data-preview-state=error] canvas{opacity:.3}.fc-lens[data-preview-state=pending] .viewport::after,.fc-lens[data-preview-state=error] .viewport::after{content:'Updating preview…';position:absolute;left:12px;top:12px;padding:6px 10px;background:#25222de8;border:1px solid #65533a;color:#f5ce93;border-radius:4px;font-size:12px;pointer-events:none}.fc-lens[data-preview-state=error] .viewport::after{content:'Preview unavailable · previous image'}.fc-lens .optics.stale .diagram{opacity:.45}
.fc-lens .look-card{min-height:62px;padding:8px 10px;gap:3px}.fc-lens .current-look{margin:9px 0 14px}.fc-lens .eyebrow{margin-bottom:8px}.fc-lens .field{margin:12px 0}.fc-lens .output-select{display:flex;align-items:center;gap:5px;font-size:11px;color:#aaaab8}.fc-lens .output-select select{width:166px;font-size:12px;min-height:34px;margin-left:3px}
.fc-lens[data-mode=advanced] .center{display:grid;grid-template-columns:minmax(0,1.08fr) minmax(0,1fr);grid-template-rows:auto minmax(120px,1fr) auto auto;align-items:stretch;gap:10px 14px}.fc-lens[data-mode=advanced] .preview-heading{grid-column:1;grid-row:1;flex-wrap:wrap}.fc-lens[data-mode=advanced] .preview-heading h3{min-width:170px}.fc-lens[data-mode=advanced] .previewspace{grid-column:1;grid-row:2}.fc-lens[data-mode=advanced] .preview-caption{grid-column:1;grid-row:3}.fc-lens[data-mode=advanced] .status{grid-column:1;grid-row:4}.fc-lens[data-mode=advanced] .optics{grid-column:2;grid-row:1/-1;display:flex;flex-direction:column;min-height:0}.fc-lens[data-mode=advanced] .optics>summary small{display:none}.fc-lens[data-mode=advanced] .optics-body{flex:1;display:flex;flex-direction:column;min-height:0}.fc-lens[data-mode=advanced] .diagram{height:auto;flex:1;min-height:120px}.fc-lens[data-mode=advanced] .diagram-footer{gap:8px;line-height:1.6}.fc-lens[data-mode=advanced] .selected-readout{margin:0;width:100%}
@media(max-width:1100px){.fc-lens[data-mode=advanced] .center{display:flex}.fc-lens[data-mode=advanced] .optics{display:block}.fc-lens[data-mode=advanced] .diagram{height:150px}.fc-lens[data-mode=advanced] .optics-body{display:block}.fc-lens[data-mode=advanced] .selected-readout{width:auto;margin-left:auto}}
@media(max-width:900px){.fc-lens .layout{grid-template-columns:245px minmax(0,1fr)}.fc-lens .sidebar{padding:12px}.fc-lens .mode-description{display:none}.fc-lens .center{padding:12px}.fc-lens .diagram{height:140px}.fc-lens .optics summary small{display:none}.fc-lens .output-select>span{display:none}}
@media(max-width:650px){.fc-lens header{padding:10px 12px}.fc-lens header .brand small{display:none}.fc-lens .modebar{padding:8px 12px}.fc-lens .layout{display:flex;flex-direction:column;overflow:auto}.fc-lens .center{order:-1;min-height:360px;overflow:visible;flex-shrink:0}.fc-lens .previewspace{min-height:180px;flex:none}.fc-lens .sidebar{overflow:visible;border-right:0}.fc-lens .look-cards{grid-template-columns:repeat(4,minmax(0,1fr))}.fc-lens .look-card{padding:7px}.fc-lens .look-card small{display:none}.fc-lens footer{padding:10px 12px;gap:8px}.fc-lens footer .muted{font-size:10px}.fc-lens .diagram-footer .selected-readout{margin-left:0}}
.fc-lens[data-mode=advanced] .optics:not([open]) .optics-body{display:none}
.fc-lens[data-mode=advanced] .center:has(>.optics:not([open])){display:flex}.fc-lens .optics-hint{margin-top:12px;padding-top:10px;border-top:1px solid #303740;color:#9eacbd;font-size:11px;line-height:1.6}
@media(max-width:650px){.fc-lens footer{flex-wrap:wrap}.fc-lens footer .muted{flex-basis:100%}.fc-lens .output-select{margin-right:auto}}
`;
